"""Add roles relation to User model

Revision ID: 78d866c7aaa8
Revises: e33751c309bc
Create Date: 2026-04-16 16:16:39.356794

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "78d866c7aaa8"
down_revision: Union[str, Sequence[str], None] = "e33751c309bc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
