"""Add deleted_at to Document for soft delete

Revision ID: 7b002935b816
Revises: ac2c0d458721
Create Date: 2026-04-24 09:49:45.715471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel



# revision identifiers, used by Alembic.
revision: str = '7b002935b816'
down_revision: Union[str, Sequence[str], None] = 'ac2c0d458721'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document', 'deleted_at')
    # ### end Alembic commands ###
