"""Add refresh token table

Revision ID: ac2c0d458721
Revises: d34dd121c6be
Create Date: 2026-04-22 06:33:43.916115

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "ac2c0d458721"
down_revision: Union[str, Sequence[str], None] = "d34dd121c6be"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "refreshtoken",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("token", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("is_revoked", sa.Boolean(), nullable=False),
        sa.Column("is_used", sa.Boolean(), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_refreshtoken_id"), "refreshtoken", ["id"], unique=False)
    op.create_index(
        op.f("ix_refreshtoken_token"), "refreshtoken", ["token"], unique=True
    )
    op.create_index(
        op.f("ix_refreshtoken_user_id"), "refreshtoken", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_refreshtoken_user_id"), table_name="refreshtoken")
    op.drop_index(op.f("ix_refreshtoken_token"), table_name="refreshtoken")
    op.drop_index(op.f("ix_refreshtoken_id"), table_name="refreshtoken")
    op.drop_table("refreshtoken")
    # ### end Alembic commands ###
