"""Add webhook event table

Revision ID: cdb3eefc30c6
Revises: fca2f078daa6
Create Date: 2026-04-30 11:00:09.653377

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel



# revision identifiers, used by Alembic.
revision: str = 'cdb3eefc30c6'
down_revision: Union[str, Sequence[str], None] = 'fca2f078daa6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('webhookevent',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('provider', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('event_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('payload', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('recieved_at', sa.DateTime(), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_webhookevent_event_type'), 'webhookevent', ['event_type'], unique=False)
    op.create_index(op.f('ix_webhookevent_id'), 'webhookevent', ['id'], unique=False)
    op.create_index(op.f('ix_webhookevent_provider'), 'webhookevent', ['provider'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_webhookevent_provider'), table_name='webhookevent')
    op.drop_index(op.f('ix_webhookevent_id'), table_name='webhookevent')
    op.drop_index(op.f('ix_webhookevent_event_type'), table_name='webhookevent')
    op.drop_table('webhookevent')
    # ### end Alembic commands ###
