"""update content feild on document to bytes

Revision ID: d060a8cdc08a
Revises: dc959ae8f0a6
Create Date: 2026-05-14 07:06:36.903158

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = 'd060a8cdc08a'
down_revision: Union[str, Sequence[str], None] = 'dc959ae8f0a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chunk', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_chunk_embedding_hnsw'), postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')

    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.alter_column('content',
               existing_type=sa.VARCHAR(),
               type_=sa.LargeBinary(),
               existing_nullable=False,
               postgresql_using='content::bytea')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.alter_column('content',
               existing_type=sa.LargeBinary(),
               type_=sa.VARCHAR(),
               existing_nullable=False,
               postgresql_using="convert_from(content, 'utf-8')")

    with op.batch_alter_table('chunk', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_chunk_embedding_hnsw'), ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')

    # ### end Alembic commands ###
