"""Update UserRole relation

Revision ID: d34dd121c6be
Revises: 78d866c7aaa8
Create Date: 2026-04-16 16:19:00.759119

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "d34dd121c6be"
down_revision: Union[str, Sequence[str], None] = "78d866c7aaa8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
