"""add_embedding_to_chunks

Revision ID: dc959ae8f0a6
Revises: e123a64efcf1
Create Date: 2026-05-13 13:33:20.388269

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector



# revision identifiers, used by Alembic.
revision: str = 'dc959ae8f0a6'
down_revision: Union[str, Sequence[str], None] = 'e123a64efcf1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    with op.batch_alter_table('chunk', schema=None) as batch_op:
        batch_op.add_column(sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True))

    # Add HNSW index
    op.execute("""
        CREATE INDEX idx_chunk_embedding_hnsw ON chunk 
        USING hnsw (embedding vector_cosine_ops) 
        WITH (m = 16, ef_construction = 64);
    """)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # Drop HNSW index
    op.execute("DROP INDEX IF EXISTS idx_chunk_embedding_hnsw")

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chunk', schema=None) as batch_op:
        batch_op.drop_column('embedding')

    # ### end Alembic commands ###
