"""Update id feild for webhook event table

Revision ID: e123a64efcf1
Revises: cdb3eefc30c6
Create Date: 2026-04-30 11:21:46.939921

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel



# revision identifiers, used by Alembic.
revision: str = 'e123a64efcf1'
down_revision: Union[str, Sequence[str], None] = 'cdb3eefc30c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("webhookevent", schema=None) as batch_op:
        batch_op.alter_column(
            "id",
            existing_type=sa.CHAR(length=32),
            type_=sqlmodel.sql.sqltypes.AutoString(),
            existing_nullable=False,
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("webhookevent", schema=None) as batch_op:
        batch_op.alter_column(
            "id",
            existing_type=sqlmodel.sql.sqltypes.AutoString(),
            type_=sa.CHAR(length=32),
            existing_nullable=False,
        )
    # ### end Alembic commands ###
