"""Add is_default to UserRole

Revision ID: e4229b0e3b08
Revises: 7b002935b816
Create Date: 2026-04-24 22:18:18.187013

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel # noqa: F401



# revision identifiers, used by Alembic.
revision: str = 'e4229b0e3b08'
down_revision: Union[str, Sequence[str], None] = '7b002935b816'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('userrole', sa.Column('is_default', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('userrole', 'is_default')
    # ### end Alembic commands ###
