"""Add deleted_by feild

Revision ID: f619f3606c51
Revises: e4229b0e3b08
Create Date: 2026-04-25 19:51:15.624720

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = 'f619f3606c51'
down_revision: Union[str, Sequence[str], None] = 'e4229b0e3b08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_by', sa.Uuid(), nullable=True))
        batch_op.create_foreign_key('fk_document_deleted_by_user', 'user', ['deleted_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.drop_constraint('fk_document_deleted_by_user', type_='foreignkey')
        batch_op.drop_column('deleted_by')
    # ### end Alembic commands ###
